import { Injectable } from '@angular/core';

@Injectable()
export class APP_UTILITIES {

    public static get SAMPLE_EVENT_DATA() {
        return [
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "Legal - Case Closed",
                "event_status_string": "Supplemental Report Needed",
                "event_status": 3,
                "epi_staff": "Ray Serrano",
                "affected_count": 24,
                "end_date": "Thu Jan 15 2015 19:32:49 GMT+0000 (UTC)",
                "start_date": "Wed Oct 02 2013 04:06:07 GMT+0000 (UTC)",
                "complete": false,
                "event_reference": " Valpreal",
                "event_type_string": "Surveillance",
                "event_type": 2,
                "id": 0
            },
            {
                "superevent": "",
                "legal_number": 12456,
                "legal_status": "Legal - Case Closed",
                "event_status_string": "Final Report Needed",
                "event_status": 3,
                "epi_staff": "Long Pacheco",
                "affected_count": 33,
                "end_date": "Fri May 04 2012 10:20:01 GMT+0000 (UTC)",
                "start_date": "Wed Nov 26 2014 16:02:34 GMT+0000 (UTC)",
                "complete": true,
                "event_reference": " Zensure",
                "event_type_string": "Surveillance",
                "event_type": 2,
                "id": 1
            },
            {
                "superevent": "",
                "legal_number": 12456,
                "legal_status": "N/A",
                "event_status_string": "Field and Diagnostics Ongoing",
                "event_status": 1,
                "epi_staff": "Mills Flowers",
                "affected_count": 35,
                "end_date": "Sat Jun 27 2015 23:14:51 GMT+0000 (UTC)",
                "start_date": "Fri May 24 2013 13:37:14 GMT+0000 (UTC)",
                "complete": false,
                "event_reference": " Accupharm",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 2,
                "id": 2
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "N/A",
                "event_status_string": "Supplemental Report Needed",
                "event_status": 6,
                "epi_staff": "Rosie Bass",
                "affected_count": 40,
                "end_date": "Tue Nov 26 2013 15:17:01 GMT+0000 (UTC)",
                "start_date": "Fri May 23 2014 18:59:59 GMT+0000 (UTC)",
                "complete": false,
                "event_reference": " Melbacor",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 2,
                "id": 3
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "Legal - Case Open",
                "event_status_string": "Supplemental Report Needed",
                "event_status": 5,
                "epi_staff": "Molly Hardin",
                "affected_count": 24,
                "end_date": "Sun Nov 11 2012 01:42:00 GMT+0000 (UTC)",
                "start_date": "Fri Aug 17 2012 19:53:09 GMT+0000 (UTC)",
                "complete": true,
                "event_reference": " Twiist",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 2,
                "id": 4
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "Potential Legal",
                "event_status_string": "Field Update Needed",
                "event_status": 5,
                "epi_staff": "Robinson Joyce",
                "affected_count": 24,
                "end_date": "Tue Dec 03 2013 15:32:20 GMT+0000 (UTC)",
                "start_date": "Sun Feb 19 2012 10:33:50 GMT+0000 (UTC)",
                "complete": true,
                "event_reference": " Lexicondo",
                "event_type_string": "Surveillance",
                "event_type": 1,
                "id": 5
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "Legal - Case Open",
                "event_status_string": "Final Report Needed",
                "event_status": 5,
                "epi_staff": "King Kramer",
                "affected_count": 27,
                "end_date": "Mon Oct 22 2012 03:59:37 GMT+0000 (UTC)",
                "start_date": "Sat Jul 29 2017 18:42:24 GMT+0000 (UTC)",
                "complete": false,
                "event_reference": " Intrawear",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 1,
                "id": 6
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "Potential Legal",
                "event_status_string": "New Event Record",
                "event_status": 1,
                "epi_staff": "Rhea Rowe",
                "affected_count": 37,
                "end_date": "Thu Sep 10 2015 08:48:46 GMT+0000 (UTC)",
                "start_date": "Wed Sep 13 2017 06:47:21 GMT+0000 (UTC)",
                "complete": false,
                "event_reference": " Isotrack",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 2,
                "id": 7
            },
            {
                "superevent": "",
                "legal_number": 12456,
                "legal_status": "Legal - Case Closed",
                "event_status_string": "Field Update Needed",
                "event_status": 3,
                "epi_staff": "Edwards Maxwell",
                "affected_count": 20,
                "end_date": "Sun Jun 03 2012 21:48:16 GMT+0000 (UTC)",
                "start_date": "Thu Jul 02 2015 12:22:07 GMT+0000 (UTC)",
                "complete": true,
                "event_reference": " Dancity",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 1,
                "id": 8
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "N/A",
                "event_status_string": "Final Report Needed",
                "event_status": 1,
                "epi_staff": "Lowery Marshall",
                "affected_count": 36,
                "end_date": "Sun Jan 22 2012 08:21:14 GMT+0000 (UTC)",
                "start_date": "Mon Apr 30 2012 02:50:33 GMT+0000 (UTC)",
                "complete": true,
                "event_reference": " Geoforma",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 1,
                "id": 9
            },
            {
                'superevent': "",
                "legal_number": 12456,
                "legal_status": "Legal - Case Closed",
                "event_status_string": "Field and Diagnostics Ongoing",
                "event_status": 5,
                "epi_staff": "Webster Douglas",
                "affected_count": 28,
                "end_date": "Fri Sep 12 2014 20:19:53 GMT+0000 (UTC)",
                "start_date": "Mon Apr 09 2018 06:14:54 GMT+0000 (UTC)",
                "complete": true,
                "event_reference": " Terrasys",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 2,
                "id": 10
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "Legal - Case Closed",
                "event_status_string": "Supplemental Report Needed",
                "event_status": 6,
                "epi_staff": "Workman Blair",
                "affected_count": 24,
                "end_date": "Mon Nov 11 2013 00:50:09 GMT+0000 (UTC)",
                "start_date": "Tue Feb 18 2014 22:56:31 GMT+0000 (UTC)",
                "complete": false,
                "event_reference": " Sultraxin",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 1,
                "id": 11
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "Legal - Case Closed",
                "event_status_string": "Supplemental Report Needed",
                "event_status": 1,
                "epi_staff": "Mclean Lloyd",
                "affected_count": 35,
                "end_date": "Tue Feb 27 2018 20:19:48 GMT+0000 (UTC)",
                "start_date": "Fri Nov 11 2016 19:04:01 GMT+0000 (UTC)",
                "complete": false,
                "event_reference": " Nebulean",
                "event_type_string": "Surveillance",
                "event_type": 2,
                "id": 12
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "Legal - Case Closed",
                "event_status_string": "Supplemental Report Needed",
                "event_status": 2,
                "epi_staff": "Cohen Mcbride",
                "affected_count": 37,
                "end_date": "Tue Oct 10 2017 05:23:31 GMT+0000 (UTC)",
                "start_date": "Sun Jan 06 2019 22:31:48 GMT+0000 (UTC)",
                "complete": false,
                "event_reference": " Vendblend",
                "event_type_string": "Surveillance",
                "event_type": 1,
                "id": 13
            },
            {
                "superevent": "",
                "legal_number": 12456,
                "legal_status": "N/A",
                "event_status_string": "Final Report Needed",
                "event_status": 6,
                "epi_staff": "Ortiz Christensen",
                "affected_count": 38,
                "end_date": "Mon Dec 02 2013 07:21:18 GMT+0000 (UTC)",
                "start_date": "Thu Mar 22 2018 00:23:46 GMT+0000 (UTC)",
                "complete": true,
                "event_reference": " Cyclonica",
                "event_type_string": "Surveillance",
                "event_type": 1,
                "id": 14
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "N/A",
                "event_status_string": "Supplemental Report Needed",
                "event_status": 4,
                "epi_staff": "Acevedo Graves",
                "affected_count": 34,
                "end_date": "Fri Sep 14 2012 23:51:11 GMT+0000 (UTC)",
                "start_date": "Mon Jan 02 2012 03:49:47 GMT+0000 (UTC)",
                "complete": false,
                "event_reference": " Kaggle",
                "event_type_string": "Surveillance",
                "event_type": 1,
                "id": 15
            },
            {
                "superevent": "",
                "legal_number": 12456,
                "legal_status": "N/A",
                "event_status_string": "New Event Record",
                "event_status": 6,
                "epi_staff": "Deleon Gallegos",
                "affected_count": 31,
                "end_date": "Sun May 29 2016 13:34:30 GMT+0000 (UTC)",
                "start_date": "Mon Dec 11 2017 07:11:39 GMT+0000 (UTC)",
                "complete": true,
                "event_reference": " Hometown",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 1,
                "id": 16
            },
            {
                "superevent": "",
                "legal_number": 12456,
                "legal_status": "Legal - Case Open",
                "event_status_string": "Completed by Owner",
                "event_status": 6,
                "epi_staff": "Morse Stevens",
                "affected_count": 31,
                "end_date": "Wed Jun 10 2015 08:03:42 GMT+0000 (UTC)",
                "start_date": "Fri Mar 29 2013 02:18:42 GMT+0000 (UTC)",
                "complete": false,
                "event_reference": " Orboid",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 2,
                "id": 17
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "Legal - Case Open",
                "event_status_string": "Field and Diagnostics Ongoing",
                "event_status": 3,
                "epi_staff": "Gates Case",
                "affected_count": 32,
                "end_date": "Sat Jan 06 2018 13:22:36 GMT+0000 (UTC)",
                "start_date": "Mon Jul 15 2013 16:10:19 GMT+0000 (UTC)",
                "complete": true,
                "event_reference": " Pearlesex",
                "event_type_string": "Surveillance",
                "event_type": 2,
                "id": 18
            },
            {
                "superevent": "",
                "legal_number": null,
                "legal_status": "N/A",
                "event_status_string": "Completed by Owner",
                "event_status": 5,
                "epi_staff": "Roach Allison",
                "affected_count": 30,
                "end_date": "Thu Jun 29 2017 05:10:44 GMT+0000 (UTC)",
                "start_date": "Wed Oct 12 2016 11:42:16 GMT+0000 (UTC)",
                "complete": true,
                "event_reference": " Duoflex",
                "event_type_string": "Morbidity/Mortality",
                "event_type": 1,
                "id": 19
            }
        ]
    }
};
